update debimg-helper-policy-rc.d

diff --git a/features.d/debimg-helper-policy-rc.d/DEBIAN/postrm b/features.d/debimg-helper-policy-rc.d/DEBIAN/postrm
--- a/features.d/debimg-helper-policy-rc.d/DEBIAN/postrm
+++ b/features.d/debimg-helper-policy-rc.d/DEBIAN/postrm
@@ -1,26 +1,32 @@
-#!/bin/sh -eu
+#!/bin/sh
+
+set -eu
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 case "$1" in
 	remove|purge|upgrade|disappear)
-		if [ -L /sbin/start-stop-daemon ] ; then
-			rm /sbin/start-stop-daemon
+		if [ -e /sbin/start-stop-daemon.chroot-disable-services-original ] ; then
+			mv /sbin/start-stop-daemon.chroot-disable-services-original /sbin/start-stop-daemon
 		fi
-
-		if [ -x /sbin/start-stop-daemon.REAL ] ; then
-			mv /sbin/start-stop-daemon.REAL /sbin/start-stop-daemon
-		fi
-
-		if [ -x /usr/sbin/start-stop-daemon.REAL ] ; then
-			mv /usr/sbin/start-stop-daemon.REAL /usr/sbin/start-stop-daemon
-		fi
-
-		;;
+	;;
 
 	abort-install|abort-upgrade|failed-upgrade)
-		;;
+	;;
 
 	*)
-		echo "preinst called with invalid argument '$1'" >&2
+		echo "postrm called with unknown argument \`$1'" >&2
 		exit 1
 esac
 
